### ISSUE TITLE
Ensure we also have presets set up for our services

### ISSUE THREAD

**Issue by cgwalters** [CentOS/centos-bootc#167]
Going via a default `bootc install` or bib, we don't run the preset process.

However, anaconda does.

We're going to need to ensure that all of our units (such as the autoupdate one) are added to the relevant presets.

**Comment by mrguitar** [comment]
FYI, I'm getting the same results using "bib". So I'm guessing the issue I hit may not be anaconda specific.

**Comment by cgwalters** [comment]
As far as presets, this made be go back and reread https://github.com/coreos/fedora-coreos-config/pull/77 which was...yeah, fun.

OK so here's the root problem.  I bet what you were trying to do is:
`RUN systemctl enable myservice`

And yeah...sadly unless you *also* write a preset file for `myservice` (which no one will do) it won't be enabled because systemd will run a full preset on firstboot.  Which is a behavior we are inheriting today from FCOS.  

Today, Ignition avoids pushing the complexity of presets onto users and just always writes a preset file for each enabled unit.

So...man, yeah we should probably make a plain `systemctl enable` emit a warning in this case.  I will at least document this massive footgun.

**Comment by mrguitar** [comment]
Yeah this is an interesting problem because you don't really worry about this in the container world, but it's super important on the OS side. It's one of those things that blurs the lines. We know that cloud-init & kickstart will accept this command (at least I'm pretty sure w/ bootc), but that seems far from a desired user experience.

**Comment by cgwalters** [comment]
Does this help? https://github.com/CentOS/centos-bootc/pull/169

**Comment by cgwalters** [comment]
> We know that cloud-init & kickstart will accept this command 

Yes.  The thing is though...that *only* works because no Fedora (or RHEL) derivative before Fedora CoreOS ever used `ConditionFirstboot`...see the thread going from https://github.com/systemd/systemd/issues/8268#issuecomment-410099538

The cloud-init systems *should have*...except we made them with Anaconda.  And Anaconda has always run OS configuration at build time, and hence effectively turned off the firstboot logic.

When we did FCOS it really made sense to fix this up (particularly as it flows well with Ignition) to use `ConditionFirstboot` - and that got inherited here.  But the giant difference here is that we expect configuration at build time, not runtime.

So we definitely *could* probably go back to disabling the preset-on-boot...but, I dunno...it's actually really nice for other reasons to know "this is the first boot".

I think what we want in the end probably is:

- `systemctl enable --static hello-world.service` that just does the `ln -s` in `/usr` per above
- Fix `systemctl enable hello-world.service` to potentially detect the case where there's no corresponding preset and error out or at least warn loudly

There is also the option of changing what `systemctl enable` does by default in our images...but I'm a bit wary to touch that, even if it is a huge foot-gun.

**Comment by cgwalters** [comment]
For anyone who has a R4E system handy, do you see e.g.
```
$ journalctl -t systemd --grep=first
Jan 19 19:25:54 localhost systemd[1]: Detected first boot.
```
?

**Comment by cgwalters** [comment]
cc @runcom too

**Comment by rhatdan** [comment]
Is this just a problem with ISO installs or would it be a problem with AMI, QCOW2 ...

**Comment by mrguitar** [comment]
I believe it's a problem for all image types with eln. My early el9 tests
didn't hit this.

**Comment by cgwalters** [comment]
I believe this is fixed by https://github.com/CentOS/centos-bootc/pull/169

> My early el9 tests didn't hit this.

OK so one thing going on here is that actually Anaconda (unlike bib) will suppress `ConditionFirstboot` because it sets up `/etc/machine-id` at install time, before reboot.

This is going to be somewhat of a trap because it bifurcates the deployment story, as `ConditionFirstboot`  will work in virtualized scenarios (or, actually where `bootc install` is used to metal, bypassing Anaconda) but not Anaconda.  And bare `systemctl enable` invocations will work in container images and kickstarts using Anaconda, but not bib or `bootc install`.

**Comment by miabbott** [comment]
> journalctl -t systemd --grep=first
> Jan 19 19:25:54 localhost systemd[1]: Detected firs

On a R4E system that I built using 9.4 beta:

```
$ journalctl -t systemd --grep=first
Dec 01 16:51:50 localhost systemd[1]: First Boot Wizard was skipped because of an unmet condition check (ConditionFirstBoot=yes).
Dec 01 16:51:51 localhost systemd[1]: First Boot Complete was skipped because of an unmet condition check (ConditionFirstBoot=yes).
Dec 01 16:51:51 localhost systemd[1]: Mark Ignition Boot Complete was skipped because of an unmet condition check (ConditionKernelCommandLine=ignition.firstboot).
-- Boot 3137480c3cf441e0a9218f883762137e --
Dec 07 14:59:26 miabbott-rhel94-edge systemd[1]: First Boot Wizard was skipped because of an unmet condition check (ConditionFirstBoot=yes).
Dec 07 14:59:26 miabbott-rhel94-edge systemd[1]: First Boot Complete was skipped because of an unmet condition check (ConditionFirstBoot=yes).
Dec 07 14:59:27 miabbott-rhel94-edge systemd[1]: Mark Ignition Boot Complete was skipped because of an unmet condition check (ConditionKernelCommandLine=ignition.firstboot).
-- Boot a3aaf7b89d1c4196ba7726452168d6a5 --
Jan 23 15:59:39 miabbott-rhel94-edge systemd[1]: First Boot Wizard was skipped because of an unmet condition check (ConditionFirstBoot=yes).
Jan 23 15:59:39 miabbott-rhel94-edge systemd[1]: First Boot Complete was skipped because of an unmet condition check (ConditionFirstBoot=yes).
Jan 23 15:59:40 miabbott-rhel94-edge systemd[1]: Mark Ignition Boot Complete was skipped because of an unmet condition check (ConditionKernelCommandLine=ignition.firstboot).
```

**Comment by nzwulfin** [comment]
> I believe this is fixed by #169

I was doing some manual testing to incorporate the preset approach [in my scenario,](https://github.com/nzwulfin/bootc-django/tree/main) b/c i have a mix of distro shipped packages and custom unit file I'm enabling. I'm also enabling them via ansible not the Containerfile, so there's maybe lots of edge cases here. 

What I'm finding is that simply stopping and re-starting the container is removing the links from `/etc/systemd/multiuser.target.wants` without ever attempting an image build. Is this the same root cause?  Committing the running container with the enabled units to a new target also results in the same behavior.

```
[core@bootc-builder bootc-django]$ podman start atest
atest
[core@bootc-builder bootc-django]$ podman exec -it atest /bin/bash
bash-5.2# systemctl enable nginx postgresql
Created symlink /etc/systemd/system/multi-user.target.wants/nginx.service → /usr/lib/systemd/system/nginx.service.
Created symlink /etc/systemd/system/multi-user.target.wants/postgresql.service → /usr/lib/systemd/system/postgresql.service.

bash-5.2# ls /etc/systemd/system/multi-user.target.wants/
NetworkManager.service	nginx.service		     sshd.service
chronyd.service		ostree-finalize-staged.path  sssd.service
irqbalance.service	postgresql.service	     systemd-homed.service
mdmonitor.service	remote-cryptsetup.target     systemd-oomd.service
nfs-client.target	remote-fs.target

[core@bootc-builder bootc-django]$ podman stop atest
atest
[core@bootc-builder bootc-django]$ podman start atest
atest
[core@bootc-builder bootc-django]$ podman exec -it atest /bin/bash
bash-5.2# ls /etc/systemd/system/multi-user.target.wants/
NetworkManager.service	nfs-client.target	     sshd.service
chronyd.service		ostree-finalize-staged.path  sssd.service
irqbalance.service	remote-cryptsetup.target     systemd-homed.service
mdmonitor.service	remote-fs.target	     systemd-oomd.service

bash-5.2# systemctl status nginx postgresql
○ nginx.service - The nginx HTTP and reverse proxy server
     Loaded: loaded (/usr/lib/systemd/system/nginx.service; disabled; preset: d>
    Drop-In: /usr/lib/systemd/system/service.d
             └─10-timeout-abort.conf
     Active: inactive (dead)

○ postgresql.service - PostgreSQL database server
     Loaded: loaded (/usr/lib/systemd/system/postgresql.service; disabled; pres>
    Drop-In: /usr/lib/systemd/system/service.d
             └─10-timeout-abort.conf
     Active: inactive (dead)
```

**Comment by mrguitar** [comment]
I don't get that same behavior when just running the bash as the process
for the container. I'm guessing you're running /bin/init as pid one and I
suspect if you echo something into /etc/machine-id you won't get bit by the
systemd presets "fixing" what gets run on first boot.

**Comment by nzwulfin** [comment]
I ran a few tests and it looks like it is all tied to `/etc/machine-id` state. I'm going to see if there's another way to use the ansible connection without running `/sbin/init` in the container, and how to use the preset approach. There's at least one other thing in the config that could do with some 'on first boot' style logic.

**Comment by rhatdan** [comment]
Would it make sense to have ansible remove the file if it knows it is running within a container?

**Comment by nzwulfin** [comment]
The stop / start test was just a local 'inner loop' convenience thing really, so I thought about setting a machine-id at the start of the ansible run and then removing it at the end, but that still left the services disabled in the downstream VM.

I settled on adding the [preset via the Containerfile](https://github.com/nzwulfin/bootc-django/blob/main/bootc/Containerfile) since I had a known set of services. That worked to get everything available during the ansible run, local manual testing, and in via QCOW import and kickstart install on a different machine.  

There's _probably_ a better way to run the ansible playbooks than needing a live container to modify, but I'm not sure what that is.

**Comment by lnykryn** [comment]
Is there a definition of what you need to do on a real first boot? Maybe on systemd side we can add knobs to make this more granular. I mean, for example, add an option to systemd.conf to set if we should do the full preset on firstboot.

**Comment by cgwalters** [comment]
In our default base image, it's unused:

```
$ podman run --rm -ti quay.io/centos-bootc/centos-bootc:stream9 grep -r ConditionFirstBoot 
/usr/lib/systemd/system/first-boot-complete.target:ConditionFirstBoot=yes
/usr/lib/systemd/system/systemd-firstboot.service:ConditionFirstBoot=yes
```

So, we could default to reverting to the status quo of Fedora derivatives and turn it off by putting an empty `/etc/machine-id` in our containers.

That would have the effect that a plain `systemctl enable myservice` would Just Work without caring about presets across the board - and it would bring us into consistency with Anaconda.

*But* I like the firstboot concept...there's a lot of things which one might want to hook into firstboot in general.  OTOH, one can emulate "firstboot" by doing an "idempotence" approach anyways for individual services.  (Which is arguably more robust)

The anaconda consistency argument though may drive us to doing the above though, and we can document how to just `RUN /etc/machine-id` in a derived container image to turn back on firstboot (except for anaconda...which hmm we're probably going to need some kickstart option to stop it from writing `/etc/machine-id).

**Comment by nzwulfin** [comment]
Coming at this as a poorly informed user, is there a reason we shouldn't just ask anaconda to set `machine-id` as `unconfigured` during install?  Are there things anaconda does that depends on a valid `machine-id`?

**Comment by cgwalters** [comment]
Yeah, it's easy [to do in a %post](https://pagure.io/fedora-kickstarts/blob/main/f/fedora-cloud-base.ks#_155).

**Comment by rhatdan** [comment]
I would prefer that `RUN systemctl enable myservice ` Just work as it would within the container.

**Comment by cgwalters** [comment]
Dan and I had a sync on this and I am I guess now convinced that for now, in order to achieve consistency with Anaconda *and* to unbreak `RUN systemctl enable foo` in container builds, we should change our base image to have an empty `machine-id` and hence disable `ConditionFirstBoot=` and consequently disable the preset run on firstboot.

I honestly liked that we'd achieved `ConditionFirstBoot` being useful in a Fedora derivative but...in the end we only did some minor stuff with it in FCOS so it's not a big loss.  (Of course this is circular as because it's never been enabled by default, it can't be used, but anyways)

**Comment by mrguitar** [comment]
I really like this outcome, and if I understand correctly users can still
opt-into using presets if they generate something for the machine-id. That
sounds like a great default to users who aren't advanced, and those that
are will still be able to use presets when they need to.
