### ISSUE TITLE
SSH Key: Won't let me type a new Passphrase

### ISSUE THREAD

**Issue by WVPrimrose** [CentOS/centos-bootc#249]
Hey guys,

I'm trying to create a new SSH key, and I used the following steps to try and create it.

ssh-keygen -t ed25519 -C "kzbindy@hotmail.com"
I then entered the file which I wanted to save it, which is under coding, but when it asked me to enter in a passphrase, it won't let me type anything.  Do you know what's going on? 
![Screenshot (101)](https://github.com/CentOS/centos-bootc/assets/158582360/9e25d1dc-414c-49e0-a6ba-730befb4f597)
![Screenshot (101)](https://github.com/CentOS/centos-bootc/assets/158582360/fc392c94-4755-476b-bee9-43d418fa822e)

**Comment by cgwalters** [comment]
This is not a general CentOS support repository, sorry.
