### ISSUE TITLE
Add "how to create a Containerfile" doc

### ISSUE THREAD

**Issue by cdrage** [CentOS/centos-bootc#365]
We created some documentation here on how to create a Containerfile: https://github.com/containers/podman-desktop-extension-bootc/blob/main/docs/containerfile_guide.md

Which should instead be in this repo.

Some of the points in the document is outdated, but the examples and the explanations are beneficial in order to get others understanding the concepts of building a "bootc os container"

**Comment by cgwalters** [comment]
Definitely, there's some of that in https://centos.github.io/centos-bootc/builds/ that should be merged together.

There's also https://gitlab.com/bootc-org/examples that we should be linking more prominently.

**Comment by cgwalters** [comment]
I think this is covered somewhat by the above.
