### ISSUE TITLE
Consider switching to CMD /sbin/init

### ISSUE THREAD

**Issue by cgwalters** [CentOS/centos-bootc#449]
We've been having a chat about switching to running via systemd by default, i.e. we do 

```
CMD /sbin/init
STOPSIGNAL SIGRTMIN+3
```

in the base image.  

I was a little uncertain about it at first...hard to describe why, it may be just a lack of familiarity with working with containers in that flow.  Perhaps it just makes sense.

**Comment by rhatdan** [comment]
Yes this should be the default.

**Comment by rhatdan** [comment]
I thought I opened an issue on this months ago, but can not find it.
