### ISSUE TITLE
Bump Podman version to v5.0.0

### ISSUE THREAD

**Issue by Gregory-Pereira** [CentOS/centos-bootc#496]
Centos Bootc is used as the parent image for many of our other bootc images in [ai-lab-recipes](https://github.com/containers/ai-lab-recipes) repo, that attempt to make pull in sizeable images, sometimes resulting in network issues like `connection reset by peer`. For this reason I would like to petition to bump Podman to version `v5.0.0` so that we can leverage the `--retry` flag in `podman pull`. 

/cc @rhatdan

**Comment by Gregory-Pereira** [comment]
Based on my cursory first look, this seems like an upstream issue, that apt Ubuntu 22.04 doesn’t serve anything newer, and the build workflows are currently using [a manual way](https://github.com/CentOS/centos-bootc/blob/fb7824ca748e5fff87dfe8c3cb85761a6bd82f04/.github/workflows/build-image.yml#L25-L32) to bypass the [default version of podman for Ubuntu 22.04 LTS](https://podman.io/blogs/2022/04/05/ubuntu-2204-lts-kubic.html). Not sure this is possible but let me know if I am misunderstanding anything. 
[Related podman issue](https://github.com/containers/podman/issues/14065) where something similar was brought up

**Comment by cgwalters** [comment]
Note that this project is intending to *be* CentOS.  We aren't going to cherry pick a major new upstream version bump into this base image.

Of course, anyone can create a derived image which bumps the podman version as they like.

Remember [centos stream is RHEL](https://www.redhat.com/en/blog/furthering-evolution-centos-stream)

**Comment by Gregory-Pereira** [comment]
Understood thanks for clarification, seems like this is a misunderstanding on my part.
